schema: schema.graphqls
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://api.kick.com/public/v1/graphql
      headers:
        Client-ID: kick-public-client
      introspect: false
