package z0;

public enum a {
    PENALTY_LOG,
    PENALTY_DEATH,
    DETECT_FRAGMENT_REUSE,
    DETECT_FRAGMENT_TAG_USAGE,
    DETECT_WRONG_NESTED_HIERARCHY,
    DETECT_TARGET_FRAGMENT_USAGE,
    DETECT_WRONG_FRAGMENT_CONTAINER
}
