name: Android CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install Android SDK components
      run: |
        ANDROID_SDK_ROOT="$HOME/android-sdk"
        ANDROID_HOME="$ANDROID_SDK_ROOT"
        mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools"
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o /tmp/cmdline-tools.zip
        unzip -q /tmp/cmdline-tools.zip -d "$ANDROID_SDK_ROOT/cmdline-tools"
        rm -rf "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        mv "$ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools" "$ANDROID_SDK_ROOT/cmdline-tools/latest"
        rm /tmp/cmdline-tools.zip
        echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
        export ANDROID_SDK_ROOT ANDROID_HOME
        yes | "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
        "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" --sdk_root="$ANDROID_SDK_ROOT" --install "platforms;android-36" "build-tools;36.0.0"
    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk

    - name: Update git tag
      run: |
        git tag -f latest
        git push -f origin latest

    - name: Delete Release
      uses: cb80/delrel@latest
      with:
        tag: latest

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: app/build/outputs/apk/release/*.apk
        generateReleaseNotes: false
        makeLatest: true
        tag: "latest"
